[package]
name = "spwn"
version = "0.0.6"
authors = ["Spu7Nix <main@spu7nix.net>"]
edition = "2018"
description = "A language for Geometry Dash triggers"
readme = "README.md"
homepage = "https://spu7nix.net/spwn/"
repository = "https://github.com/Spu7Nix/SPWN-language/"
license-file = "LICENSE"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "spwn"
path = "src/main.rs"

[dependencies]
quick-xml = "0.22.0"
base64 = "0.13.0"
libflate = "1.1.0"
lazy_static = "1.4.0"
crc32fast = "1.2.0"
logos = "0.12.0"
termcolor = "1.1.2"
text_io = "0.1.8"
regex = "1.5.4"
slyce = "0.3.1"
rand = "0.8.4"
tempfile = "3.2.0"

internment = "0.5.4"

ariadne = "0.1.3" # errors

aes = "0.7.4"
block-modes = "0.8.1"

itertools = "0.10.1"
cached = "0.25.0"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
toml = "0.5.7"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.8.2"
libc = "0.2.81"

[target.'cfg(target_os = "windows")'.dependencies]
 named_pipe = "0.4.1"

# heat dir libraries -o wix/libraries.wxs -scom -frag -srd -sreg -gg -cg libraries -dr LIB_DIR -suid