[package]
name = "spwn"
version = "0.0.85"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
ariadne = "0.1.5"
slotmap = "1.0.6"
ansi_term = "0.12.1"
regex = "1.5.6"