[package]
name = "levelstring"
version = "0.0.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

quick-xml = "0.22.0"
base64 = "0.13.0"
libflate = "1.1.0"
crc32fast = "1.2.0"

aes = "0.7.4"
block-modes = "0.8.1"
